apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-vildcxyt
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-vildcxyt:af4147612e8d6803eaaef6f18ee01a1ed19f19fb@sha256:ea8d5da87018fa2ae24c8840b1c2c83523f78e23f0581b9ebad658f4dea12c00
        name: container-image  
